services:
  database:
    restart: always
    image: mysql:8
    container_name: RCWAI-backend-database
    env_file: .env
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ~/RCWAI-backend/database:/var/lib/mysql

  app:
    build: .
    restart: always
    container_name: RCWAI-backend-app
    env_file: .env
    environment:
      DB_HOST: database
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - database